import sys
from unittest.mock import patch, MagicMock

import pytest

from pyplaner.__main__ import main


@pytest.fixture()
def simple_template(tmp_path):
    tpl = tmp_path / "planner.html"
    tpl.write_text(
        "<html>{{ planner_head }}\n"
        "%% for y in range(2026, 2027)\n"
        "%% set year = calendar.year(y)\n"
        "{{ year }}\n"
        "%% endfor\n"
        "</html>",
        encoding="utf-8",
    )
    return tpl


def test_generates_html(simple_template, tmp_path):
    """--html with an explicit path writes rendered HTML to that file."""
    out = tmp_path / "out.html"
    with patch.object(sys, "argv", [
        "pyplaner", str(simple_template), "--html", str(out), "-q",
    ]):
        main()
    assert out.exists()
    content = out.read_text(encoding="utf-8")
    assert "2026" in content


def test_default_html_filename(simple_template, tmp_path, monkeypatch):
    """--html without a filename defaults to <template_stem>.html."""
    monkeypatch.chdir(tmp_path)
    with patch.object(sys, "argv", [
        "pyplaner", str(simple_template), "--html", "-q",
    ]):
        main()
    out = tmp_path / "planner.html"
    assert out.exists()


def test_no_flags_generates_pdf_by_default(simple_template):
    """When neither --html nor --pdf is given, PDF is generated by default."""
    with patch.object(sys, "argv", [
        "pyplaner", str(simple_template), "-q",
    ]):
        with patch("pyplaner.__main__.Planer") as mock_planer_cls:
            mock_instance = MagicMock()
            mock_instance.pdf.return_value = b"%PDF-1.4"
            mock_planer_cls.return_value = mock_instance

            with patch("builtins.open", MagicMock()):
                main()

            mock_instance.pdf.assert_called_once()


def test_country_sets_provider(simple_template, tmp_path):
    """--country ru loads the isdayoff provider and generates output."""
    out = tmp_path / "out.html"
    with patch.object(sys, "argv", [
        "pyplaner", str(simple_template),
        "--html", str(out),
        "--country", "ru",
        "-q",
    ]):
        with patch("pyplaner.providers.isdayoff.IsDayOffProvider.fetch_day_info",
                    return_value={}):
            main()
    assert out.exists()


def test_unsupported_country_raises(simple_template):
    """--country with a code rejected by all providers raises ValueError."""
    mock_cls = type("RejectAll", (), {
        "__init__": lambda self, cc: (_ for _ in ()).throw(ValueError(cc)),
        "fetch_day_info": lambda self, y: {},
    })

    with patch.object(sys, "argv", [
        "pyplaner", str(simple_template),
        "--html",
        "--country", "zz",
        "--provider", "some_module",
        "-q",
    ]):
        with patch("pyplaner.dayinfo.DayInfoProvider.load",
                    return_value=[mock_cls]):
            with pytest.raises(ValueError, match="No day-info provider found"):
                main()


def test_explicit_weekday_override(simple_template, tmp_path):
    """--first-weekday sunday overrides the country default."""
    out = tmp_path / "out.html"
    with patch.object(sys, "argv", [
        "pyplaner", str(simple_template),
        "--html", str(out),
        "--first-weekday", "sunday",
        "-q",
    ]):
        main()
    assert out.exists()


def test_numeric_weekday(simple_template, tmp_path):
    """--first-weekday 6 sets Sunday as the first weekday."""
    out = tmp_path / "out.html"
    with patch.object(sys, "argv", [
        "pyplaner", str(simple_template),
        "--html", str(out),
        "--first-weekday", "6",
        "-q",
    ]):
        main()
    assert out.exists()


def test_russian_language(simple_template, tmp_path):
    """--lang ru generates output using Russian locale data."""
    out = tmp_path / "out.html"
    with patch.object(sys, "argv", [
        "pyplaner", str(simple_template),
        "--html", str(out),
        "--lang", "ru",
        "-q",
    ]):
        main()
    assert out.exists()
