import os
import pathlib
from urllib.parse import urlparse, unquote

import jinja2
from playwright.sync_api import Route, sync_playwright

from .calendar import Calendar
from .tracker import tracker


def _asset_route(r: Route) -> None:
    """Route requests generated by the browser to the local file system.

    :param r: Playwright :class:`~playwright.sync_api.Route` to fulfill.
    """
    parse_result = urlparse(r.request.url)
    path = unquote(parse_result.path)

    if parse_result.netloc:
        # file://hostname/path -> ignore hostname for local files
        path = f"{parse_result.netloc}{path}"
    elif path.startswith("/") and ":" in path[1:3]:
        # Windows: strip leading slash in /C:/path
        path = path[1:]

    r.fulfill(path=path)


class Planner:
    """Render a Jinja2/HTML planner template into HTML or PDF.

    :param path: Path to the Jinja2/HTML template file.
    :param calendar: :class:`~pyplanner.calendar.Calendar` instance used for
        template rendering.
    """

    def __init__(self, path: str | os.PathLike,
                 calendar: Calendar | None = None,
                 ) -> None:
        if calendar is None:
            calendar = Calendar()
        self.calendar = calendar
        self.path = pathlib.Path(path).absolute()

        self._env = jinja2.Environment(
            loader=jinja2.FileSystemLoader(self.path.parent),
            autoescape=jinja2.select_autoescape(),
            trim_blocks=True,
            lstrip_blocks=True,
            line_statement_prefix="%%",
            line_comment_prefix="##"
        )

    def html(self, base: str | None = None) -> str:
        """Render the template and return the resulting HTML string.

        :param base: Base URL used to resolve assets paths. If not provided,
            the planner directory is used. During live reloading, browser
            doesn't generate requests for file:// URLs. This parameter is used
            to provide a base URL relative to the output directory. In this
            case, both live reloading and preview in browser will work.
        :returns: Rendered HTML.
        """
        if base is None:
            base = self.path.parent.as_uri()

        tracker().job("Render HTML")
        return self._env.get_template(self.path.name).render(
            base=base,
            calendar=self.calendar,
            lang=self.calendar.lang,
        )

    def pdf(self, base: str | None = None) -> bytes:
        """Render the template and return a PDF as raw bytes.

        :param base: Base URL used to resolve assets paths. If not provided, the
            planner directory is used.
        :returns: PDF file content as bytes.
        """
        if base is None:
            base = self.path.parent.as_uri()

        with tracker().job("Render HTML"):
            html = self._env.get_template(self.path.name).render(
                base=base,
                calendar=self.calendar,
                lang=self.calendar.lang,
            )

        with sync_playwright() as p:
            with tracker().job("Launch browser"):
                browser = p.chromium.launch(args=[
                    "--allow-file-access-from-files",
                    "--disable-web-security",
                ])
            with tracker().job("Set page content"):
                page = browser.new_page()
                page.on("requestfailed",
                        lambda r: print(f'Failed to load "{r.url}"')
                )
                page.route("file://**/*", _asset_route)
                page.set_content(html, wait_until="load")
                page.evaluate("() => document.fonts.ready")
            with tracker().job("Print page to PDF"):
                pdf = page.pdf(print_background=True, prefer_css_page_size=True)

            browser.close()

        return pdf
