import io
import os
import pathlib
from urllib.parse import urlparse, unquote

import jinja2
from playwright.sync_api import Route, sync_playwright

from .calendar import Calendar
from .progress import ProgressTracker, QuietTracker

try:
    import pikepdf
    from .optimize_pdf import optimize_pdf
except ImportError:
    pikepdf = None  # type: ignore[assignment]


def _asset_route(r: Route) -> None:
    """Route requests generated by the browser to the local file system.

    :param r: Playwright :class:`~playwright.sync_api.Route` to fulfill.
    """
    parse_result = urlparse(r.request.url)
    path = unquote(parse_result.path)

    if parse_result.netloc:
        # file://hostname/path -> ignore hostname for local files
        path = f"{parse_result.netloc}{path}"
    elif path.startswith("/") and ":" in path[1:3]:
        # Windows: strip leading slash in /C:/path
        path = path[1:]

    r.fulfill(path=path)


class Planner:
    """Render a Jinja2/HTML planner template into HTML or PDF.

    :param path: Path to the Jinja2/HTML template file.
    :param planner_dir: Base URL or path to the template directory.
    :param calendar: :class:`~pyplanner.calendar.Calendar` instance used for
        template rendering.
    """

    def __init__(self, path: str | os.PathLike,
                 planner_dir: str | os.PathLike | None = None,
                 calendar: Calendar | None = None,
    ) -> None:
        if calendar is None:
            calendar = Calendar()
        self.calendar = calendar

        self.path = pathlib.Path(path).absolute()

        if planner_dir is None:
            planner_dir = self.path.parent.as_uri()
        self.planner_dir = str(planner_dir)

        self._env = jinja2.Environment(
            loader=jinja2.FileSystemLoader(self.path.parent),
            autoescape=jinja2.select_autoescape(),
            trim_blocks=True,
            lstrip_blocks=True,
            line_statement_prefix="%%",
            line_comment_prefix="##"
        )

    def html(self, tracker: ProgressTracker | None = None) -> str:
        """Render the template and return the resulting HTML string.

        :param tracker: Optional progress tracker.
        :returns: Rendered HTML.
        """
        if tracker is None:
            tracker = QuietTracker()
        tracker.job("html render")
        return self._env.get_template(self.path.name).render(
            base=self.planner_dir,
            calendar=self.calendar,
            lang=self.calendar.lang,
        )

    def pdf(self,
            margin_top: str | float | None = None,
            margin_right: str | float | None = None,
            margin_bottom: str | float | None = None,
            margin_left: str | float | None = None,
            pdf_optimize: bool = True,
            tracker: ProgressTracker | None = None,
            ) -> bytes:
        """Render the template and return a PDF as raw bytes.

        :param margin_top: Top page margin (CSS length or ``None``).
        :param margin_right: Right page margin (CSS length or ``None``).
        :param margin_bottom: Bottom page margin (CSS length or ``None``).
        :param margin_left: Left page margin (CSS length or ``None``).
        :param pdf_optimize: If ``True`` (default) and ``pikepdf`` is
            available, post-process the PDF to deduplicate images and
            strip obsolete metadata.
        :param tracker: Optional progress tracker.
        :returns: PDF file content as bytes.
        """
        if tracker is None:
            tracker = QuietTracker()

        job_count = 4
        if pikepdf is not None:
            job_count += 1
        tracker.set_job_count(job_count)

        tracker.job("html render")
        html = self._env.get_template(self.path.name).render(
            base=self.planner_dir,
            calendar=self.calendar,
            lang=self.calendar.lang,
        )

        with sync_playwright() as p:
            tracker.job("browser launch")
            browser = p.chromium.launch(args=[
                "--allow-file-access-from-files",
                "--disable-web-security",
            ])

            page = browser.new_page()
            page.on("requestfailed",
                lambda r: print(f'Failed to load "{r.url}"'))
            page.route("file://**/*", _asset_route)

            tracker.job("set content")
            page.set_content(html, wait_until="load")
            page.evaluate("() => document.fonts.ready")

            tracker.job("page pdf")
            pdf = page.pdf(
                print_background=True,
                prefer_css_page_size=True,
                margin={
                    "top": margin_top,
                    "right": margin_right,
                    "bottom": margin_bottom,
                    "left": margin_left,
                },
            )

            browser.close()

        if pikepdf is None:
            return pdf

        tracker.job("pikepdf")
        with pikepdf.open(io.BytesIO(pdf)) as pike_pdf_obj:
            if pdf_optimize:
                optimize_pdf(pike_pdf_obj)
            bio = io.BytesIO()
            pike_pdf_obj.save(bio,
                object_stream_mode=pikepdf.ObjectStreamMode.generate,
                recompress_flate=True,
            )
            return bio.getvalue()
